-- Esquema del Sistema de Facturación de Pasteles (compatible con PostgreSQL y H2 en modo PostgreSQL)
-- Es idempotente: puede ejecutarse varias veces.

CREATE TABLE IF NOT EXISTS categorias (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL UNIQUE,
    descripcion  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS clientes (
    id_cliente          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_identidad VARCHAR(30)  NOT NULL UNIQUE,
    nombre_completo     VARCHAR(150) NOT NULL,
    telefono            VARCHAR(30)  NOT NULL,
    correo              VARCHAR(150) NOT NULL,
    estado              VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT ck_clientes_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS productos (
    id_producto  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_unico VARCHAR(50)   NOT NULL UNIQUE,
    nombre       VARCHAR(150)  NOT NULL,
    id_categoria BIGINT        NOT NULL,
    precio       DECIMAL(12,2) NOT NULL,
    stock        INT           NOT NULL,
    estado       VARCHAR(10)   NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT fk_productos_categoria FOREIGN KEY (id_categoria) REFERENCES categorias (id_categoria),
    CONSTRAINT ck_productos_precio CHECK (precio > 0),
    CONSTRAINT ck_productos_stock  CHECK (stock >= 0),
    CONSTRAINT ck_productos_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE SEQUENCE IF NOT EXISTS seq_numero_factura START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS facturas (
    id_factura       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_factura   VARCHAR(30)   NOT NULL UNIQUE,
    fecha_emision    TIMESTAMP     NOT NULL,
    id_cliente       BIGINT        NOT NULL,
    usuario_authcore VARCHAR(100)  NOT NULL,
    total            DECIMAL(14,2) NOT NULL,
    estado_factura   VARCHAR(10)   NOT NULL DEFAULT 'EMITIDA',
    CONSTRAINT fk_facturas_cliente FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT ck_facturas_total  CHECK (total >= 0),
    CONSTRAINT ck_facturas_estado CHECK (estado_factura IN ('EMITIDA', 'ANULADA'))
);

CREATE TABLE IF NOT EXISTS detalles_factura (
    id_detalle      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura      BIGINT        NOT NULL,
    id_producto     BIGINT        NOT NULL,
    cantidad        INT           NOT NULL,
    precio_unitario DECIMAL(12,2) NOT NULL,
    subtotal        DECIMAL(14,2) NOT NULL,
    CONSTRAINT fk_detalles_factura  FOREIGN KEY (id_factura)  REFERENCES facturas (id_factura),
    CONSTRAINT fk_detalles_producto FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT ck_detalles_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalles_precio   CHECK (precio_unitario > 0),
    CONSTRAINT ck_detalles_subtotal CHECK (subtotal > 0)
);

-- Índices para las consultas frecuentes (reporte mensual y carga de facturas)
CREATE INDEX IF NOT EXISTS idx_facturas_fecha     ON facturas (fecha_emision);
CREATE INDEX IF NOT EXISTS idx_facturas_cliente   ON facturas (id_cliente);
CREATE INDEX IF NOT EXISTS idx_detalles_factura   ON detalles_factura (id_factura);
CREATE INDEX IF NOT EXISTS idx_detalles_producto  ON detalles_factura (id_producto);
CREATE INDEX IF NOT EXISTS idx_productos_categoria ON productos (id_categoria);
