# Perfil de producción/QA con PostgreSQL:  SPRING_PROFILES_ACTIVE=postgres
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pasteleria}
spring.datasource.username=${DB_USER:pasteleria}
spring.datasource.password=${DB_PASSWORD:pasteleria}
spring.datasource.driver-class-name=org.postgresql.Driver
